### ISSUE TITLE
【Feature】Support react-native link?

### ISSUE THREAD

**Issue by Lxxyx** [songxiaoliang/react-native-feedback#1]
Support react-native link?

**Comment by songxiaoliang** [comment]
@Lxxyx emm.. I 'm sorry, currently not supported.

**Comment by Lxxyx** [comment]
嗯嗯，我能直接用这个SDK吗？还是我的SDK需要从阿里云中生成的

**Comment by songxiaoliang** [comment]
@Lxxyx 直接用即可

**Comment by Lxxyx** [comment]
我研究下 react native link，可以的话给你提个 PR
